<script lang="ts" setup>
import {
  type BadgeProps,
  RuiBadge,
  RuiButton,
} from '@rotki/ui-library-compat/components';
import { ref } from 'vue';

const badges = ref<BadgeProps[]>([
  {
    value: true,
    text: '1',
    color: 'default',
  },
  {
    value: true,
    text: '1',
    color: 'primary',
  },
  {
    value: true,
    text: '1',
    color: 'secondary',
  },
  {
    value: true,
    text: '1',
    color: 'error',
  },
  {
    value: true,
    text: '1',
    color: 'warning',
  },
  {
    value: true,
    text: '1',
    color: 'info',
  },
  {
    value: true,
    text: '1',
    color: 'success',
  },
  {
    value: true,
    text: '1',
    color: 'default',
    placement: 'bottom',
  },
  {
    value: true,
    text: '1',
    color: 'primary',
    placement: 'bottom',
  },
  {
    value: true,
    text: '1',
    color: 'secondary',
    placement: 'bottom',
  },
  {
    value: true,
    text: '1',
    color: 'error',
    placement: 'bottom',
  },
  {
    value: true,
    text: '1',
    color: 'warning',
    placement: 'bottom',
  },
  {
    value: true,
    text: '1',
    color: 'info',
    placement: 'bottom',
  },
  {
    value: true,
    text: '1',
    color: 'success',
    placement: 'bottom',
  },
  {
    value: true,
    text: '1',
    color: 'default',
    left: true,
  },
  {
    value: true,
    text: '1',
    color: 'primary',
    left: true,
  },
  {
    value: true,
    text: '1',
    color: 'secondary',
    left: true,
  },
  {
    value: true,
    text: '1',
    color: 'error',
    left: true,
  },
  {
    value: true,
    text: '1',
    color: 'warning',
    left: true,
  },
  {
    value: true,
    text: '1',
    color: 'info',
    left: true,
  },
  {
    value: true,
    text: '1',
    color: 'success',
    left: true,
  },
  {
    value: true,
    text: '1',
    color: 'default',
    left: true,
    placement: 'bottom',
  },
  {
    value: true,
    text: '1',
    color: 'primary',
    left: true,
    placement: 'bottom',
  },
  {
    value: true,
    text: '1',
    color: 'secondary',
    left: true,
    placement: 'bottom',
  },
  {
    value: true,
    text: '1',
    color: 'error',
    left: true,
    placement: 'bottom',
  },
  {
    value: true,
    text: '1',
    color: 'warning',
    left: true,
    placement: 'bottom',
  },
  {
    value: true,
    text: '1',
    color: 'info',
    left: true,
    placement: 'bottom',
  },
  {
    value: true,
    text: '1',
    color: 'success',
    left: true,
    placement: 'bottom',
  },
  {
    value: true,
    text: '1',
    color: 'default',
    icon: 'star-fill',
  },
  {
    value: true,
    text: '1',
    color: 'primary',
    icon: 'star-fill',
  },
  {
    value: true,
    text: '1',
    color: 'secondary',
    icon: 'star-fill',
  },
  {
    value: true,
    text: '1',
    color: 'error',
    icon: 'star-fill',
  },
  {
    value: true,
    text: '1',
    color: 'warning',
    icon: 'star-fill',
  },
  {
    value: true,
    text: '1',
    color: 'info',
    icon: 'star-fill',
  },
  {
    value: true,
    text: '1',
    color: 'success',
    icon: 'star-fill',
  },
  {
    value: true,
    text: '1',
    color: 'default',
    placement: 'bottom',
    icon: 'star-fill',
  },
  {
    value: true,
    text: '1',
    color: 'primary',
    placement: 'bottom',
    icon: 'star-fill',
  },
  {
    value: true,
    text: '1',
    color: 'secondary',
    placement: 'bottom',
    icon: 'star-fill',
  },
  {
    value: true,
    text: '1',
    color: 'error',
    placement: 'bottom',
    icon: 'star-fill',
  },
  {
    value: true,
    text: '1',
    color: 'warning',
    placement: 'bottom',
    icon: 'star-fill',
  },
  {
    value: true,
    text: '1',
    color: 'info',
    placement: 'bottom',
    icon: 'star-fill',
  },
  {
    value: true,
    text: '1',
    color: 'success',
    placement: 'bottom',
    icon: 'star-fill',
  },
  {
    value: true,
    text: '1',
    color: 'default',
    left: true,
    icon: 'star-fill',
    offsetX: -20,
  },
  {
    value: true,
    text: '1',
    color: 'primary',
    left: true,
    icon: 'star-fill',
    offsetX: -20,
  },
  {
    value: true,
    text: '1',
    color: 'secondary',
    left: true,
    icon: 'star-fill',
    offsetX: -20,
  },
  {
    value: true,
    text: '1',
    color: 'error',
    left: true,
    icon: 'star-fill',
    offsetX: -20,
  },
  {
    value: true,
    text: '1',
    color: 'warning',
    left: true,
    icon: 'star-fill',
    offsetX: -20,
  },
  {
    value: true,
    text: '1',
    color: 'info',
    left: true,
    icon: 'star-fill',
    offsetX: -20,
  },
  {
    value: true,
    text: '1',
    color: 'success',
    left: true,
    icon: 'star-fill',
    offsetX: -20,
  },
  {
    value: true,
    text: '1',
    color: 'default',
    left: true,
    placement: 'bottom',
    icon: 'star-fill',
    offsetX: -20,
  },
  {
    value: true,
    text: '1',
    color: 'primary',
    left: true,
    placement: 'bottom',
    icon: 'star-fill',
    offsetX: -20,
  },
  {
    value: true,
    text: '1',
    color: 'secondary',
    left: true,
    placement: 'bottom',
    icon: 'star-fill',
    offsetX: -20,
  },
  {
    value: true,
    text: '1',
    color: 'error',
    left: true,
    placement: 'bottom',
    icon: 'star-fill',
    offsetX: -20,
  },
  {
    value: true,
    text: '1',
    color: 'warning',
    left: true,
    placement: 'bottom',
    icon: 'star-fill',
    offsetX: -20,
  },
  {
    value: true,
    text: '1',
    color: 'info',
    left: true,
    placement: 'bottom',
    icon: 'star-fill',
    offsetX: -20,
  },
  {
    value: true,
    text: '1',
    color: 'success',
    left: true,
    placement: 'bottom',
    icon: 'star-fill',
    offsetX: -20,
  },
  {
    value: true,
    color: 'default',
    icon: 'star-fill',
  },
  {
    value: true,
    color: 'primary',
    icon: 'star-fill',
  },
  {
    value: true,
    color: 'secondary',
    icon: 'star-fill',
  },
  {
    value: true,
    color: 'error',
    icon: 'star-fill',
  },
  {
    value: true,
    color: 'warning',
    icon: 'star-fill',
  },
  {
    value: true,
    color: 'info',
    icon: 'star-fill',
  },
  {
    value: true,
    color: 'success',
    icon: 'star-fill',
  },
  {
    value: true,
    color: 'default',
    placement: 'bottom',
    icon: 'star-fill',
  },
  {
    value: true,
    color: 'primary',
    placement: 'bottom',
    icon: 'star-fill',
  },
  {
    value: true,
    color: 'secondary',
    placement: 'bottom',
    icon: 'star-fill',
  },
  {
    value: true,
    color: 'error',
    placement: 'bottom',
    icon: 'star-fill',
  },
  {
    value: true,
    color: 'warning',
    placement: 'bottom',
    icon: 'star-fill',
  },
  {
    value: true,
    color: 'info',
    placement: 'bottom',
    icon: 'star-fill',
  },
  {
    value: true,
    color: 'success',
    placement: 'bottom',
    icon: 'star-fill',
  },
  {
    value: true,
    color: 'default',
    left: true,
    icon: 'star-fill',
  },
  {
    value: true,
    color: 'primary',
    left: true,
    icon: 'star-fill',
  },
  {
    value: true,
    color: 'secondary',
    left: true,
    icon: 'star-fill',
  },
  {
    value: true,
    color: 'error',
    left: true,
    icon: 'star-fill',
  },
  {
    value: true,
    color: 'warning',
    left: true,
    icon: 'star-fill',
  },
  {
    value: true,
    color: 'info',
    left: true,
    icon: 'star-fill',
  },
  {
    value: true,
    color: 'success',
    left: true,
    icon: 'star-fill',
  },
  {
    value: true,
    color: 'default',
    left: true,
    placement: 'bottom',
    icon: 'star-fill',
  },
  {
    value: true,
    color: 'primary',
    left: true,
    placement: 'bottom',
    icon: 'star-fill',
  },
  {
    value: true,
    color: 'secondary',
    left: true,
    placement: 'bottom',
    icon: 'star-fill',
  },
  {
    value: true,
    color: 'error',
    left: true,
    placement: 'bottom',
    icon: 'star-fill',
  },
  {
    value: true,
    color: 'warning',
    left: true,
    placement: 'bottom',
    icon: 'star-fill',
  },
  {
    value: true,
    color: 'info',
    left: true,
    placement: 'bottom',
    icon: 'star-fill',
  },
  {
    value: true,
    color: 'success',
    left: true,
    placement: 'bottom',
    icon: 'star-fill',
  },
  {
    value: true,
    text: '1',
    color: 'default',
    dot: true,
  },
  {
    value: true,
    text: '1',
    color: 'primary',
    dot: true,
  },
  {
    value: true,
    text: '1',
    color: 'secondary',
    dot: true,
  },
  {
    value: true,
    text: '1',
    color: 'error',
    dot: true,
  },
  {
    value: true,
    text: '1',
    color: 'warning',
    dot: true,
  },
  {
    value: true,
    text: '1',
    color: 'info',
    dot: true,
  },
  {
    value: true,
    text: '1',
    color: 'success',
    dot: true,
  },
  {
    value: true,
    text: '1',
    color: 'default',
    placement: 'bottom',
    dot: true,
  },
  {
    value: true,
    text: '1',
    color: 'primary',
    placement: 'bottom',
    dot: true,
  },
  {
    value: true,
    text: '1',
    color: 'secondary',
    placement: 'bottom',
    dot: true,
  },
  {
    value: true,
    text: '1',
    color: 'error',
    placement: 'bottom',
    dot: true,
  },
  {
    value: true,
    text: '1',
    color: 'warning',
    placement: 'bottom',
    dot: true,
  },
  {
    value: true,
    text: '1',
    color: 'info',
    placement: 'bottom',
    dot: true,
  },
  {
    value: true,
    text: '1',
    color: 'success',
    placement: 'bottom',
    dot: true,
  },
  {
    value: true,
    text: '1',
    color: 'default',
    left: true,
    dot: true,
  },
  {
    value: true,
    text: '1',
    color: 'primary',
    left: true,
    dot: true,
  },
  {
    value: true,
    text: '1',
    color: 'secondary',
    left: true,
    dot: true,
  },
  {
    value: true,
    text: '1',
    color: 'error',
    left: true,
    dot: true,
  },
  {
    value: true,
    text: '1',
    color: 'warning',
    left: true,
    dot: true,
  },
  {
    value: true,
    text: '1',
    color: 'info',
    left: true,
    dot: true,
  },
  {
    value: true,
    text: '1',
    color: 'success',
    left: true,
    dot: true,
  },
  {
    value: true,
    text: '1',
    color: 'default',
    left: true,
    placement: 'bottom',
    dot: true,
  },
  {
    value: true,
    text: '1',
    color: 'primary',
    left: true,
    placement: 'bottom',
    dot: true,
  },
  {
    value: true,
    text: '1',
    color: 'secondary',
    left: true,
    placement: 'bottom',
    dot: true,
  },
  {
    value: true,
    text: '1',
    color: 'error',
    left: true,
    placement: 'bottom',
    dot: true,
  },
  {
    value: true,
    text: '1',
    color: 'warning',
    left: true,
    placement: 'bottom',
    dot: true,
  },
  {
    value: true,
    text: '1',
    color: 'info',
    left: true,
    placement: 'bottom',
    dot: true,
  },
  {
    value: true,
    text: '1',
    color: 'success',
    left: true,
    placement: 'bottom',
    dot: true,
  },
]);
</script>

<template>
  <div>
    <h2 class="text-h4 mb-6" data-cy="badges">Badges</h2>
    <div class="grid gap-6 grid-cols-3 lg:grid-cols-7">
      <div v-for="(badge, i) in badges" :key="i" class="p-4">
        <RuiBadge v-bind="badge" :data-cy="`badge-${i}`">
          <RuiButton @click="badge.value = !badge.value"> Badge </RuiButton>
        </RuiBadge>
      </div>
    </div>
  </div>
</template>
